### ISSUE TITLE
大佬, 文档配色能正常一点吗?

### ISSUE THREAD

**Issue by lynxlangya** [liub1934/lb-element-table#11]
![image](https://user-images.githubusercontent.com/28971754/59974013-7b43e600-95d9-11e9-89eb-43039a2f0057.png)

**Comment by liub1934** [comment]
不知道你用的什么浏览器 vuepress的默认颜色。
![image](https://user-images.githubusercontent.com/29849550/60475722-5ae7eb80-9cab-11e9-9860-3cea3f0637dc.png)

**Comment by lynxlangya** [comment]
![image](https://user-images.githubusercontent.com/28971754/61016334-d6d7e700-a3c1-11e9-817d-e7086ad2a414.png)
