### ISSUE TITLE
如何解析后台传来的String 类型的render函数

### ISSUE THREAD

**Issue by webjinyingying** [liub1934/lb-element-table#14]
想要做一个动态的表格，所有表格要显示的内容都是从后端传来，比如想加一个表头拖拽，这个时候用到render-header,此时render-header的内容是后端传过来的，但是是字符串，请问我该如何转换呢？谢谢~

**Comment by meko95** [comment]
你好，我也是有这个需求，请问你找到解决方法了吗

**Comment by liub1934** [comment]
这个应该是不支持的，render写法都是在打包后自动编译了，你所说的根据后台返回的render内容动态渲染应该是做不到的。
