### ISSUE TITLE
动态表头渲染出错

### ISSUE THREAD

**Issue by conderpath** [liub1934/lb-element-table#18]
多级表头时，当删除其中的某一列时整个表格都无法渲染出来了，怎么破

**Comment by liub1934** [comment]
可以暂时按下面的方法解决下,通过v-if控制表格重新渲染：
```
<lb-table v-if="showTable"></lb-table>
// 切换表头
changeColumn () {
  this.column = newColumn
  this.showTable = false
  setTimeout(() => {
      this.showTable = true
  }, 0)
}
```

**Comment by conderpath** [comment]
> 可以暂时按下面的方法解决下,通过v-if控制表格重新渲染：
> 
> ```
> <lb-table v-if="showTable"></lb-table>
> // 切换表头
> changeColumn () {
>   this.column = newColumn
>   this.showTable = false
>   setTimeout(() => {
>       this.showTable = true
>   }, 0)
> }
> ```
为什么会出现这种情况呢，强制更新也不起作用
