### ISSUE TITLE
点击行数据时会触发分页@current-change，原因是table跟分页同时有current-change事件监听

### ISSUE THREAD

**Issue by hanlife** [liub1934/lb-element-table#6]
![image](https://user-images.githubusercontent.com/21124833/58145148-a6a67e80-7c83-11e9-97fb-c11f4e7b97fe.png)
![image](https://user-images.githubusercontent.com/21124833/58145160-b2924080-7c83-11e9-842e-3bd307da741a.png)

**Comment by liub1934** [comment]
用`p-current-change`代替分页的`current-change`
