### ISSUE TITLE
element-ui更新到2.9.1，lb-column.vue提示renderHeader的propColumn为undefined

### ISSUE THREAD

**Issue by samyhd** [liub1934/lb-element-table#7]
element-ui 2.8.2正常，更新到 2.9.1后

跟踪到 lb-column.vue

    if (!this.column.renderHeader) {
      this.column.renderHeader = (h, scope, propColumn) => {
        return <span >{ propColumn.label }</span>
      }
    }

中的 propColumn 参数为 undefined 了，看到 2.9.1 中 table-column.js中有一句注释写着 “renderHeader 属性不推荐使用。”

麻烦同步下，谢谢

**Comment by liub1934** [comment]
@samyhd 已更新
```javascript
if (!this.column.render) {
      this.column.render = (h, scope) => {
        return <span>{ scope.row[scope.column.property] }</span>
      }
}
if (!this.column.renderHeader) {
    this.column.renderHeader = (h, scope) => {
        return <span>{ scope.column.label }</span>
      }
}
```

**Comment by samyhd** [comment]
我看到 forced.js 还有两处 renderHeader: (h, scope, propColumn) => ，需要一并调整吗？

还有，引起这个变动的原因是什么，谢谢

**Comment by liub1934** [comment]
> 我看到 forced.js 还有两处 renderHeader: (h, scope, propColumn) => ，需要一并调整吗？
> 
> 还有，引起这个变动的原因是什么，谢谢

应该是element覆盖掉了`renderHeader`的参数，现在都取消掉了`propColumn`
